config/routes.rb
Rails.application.routes.draw do
  resources :question_types
  get 'admin', to: 'pages#admin'
  get 'choose_age_group', to: 'pages#choose_age_group'

  get 'pages/about'

  get 'pages/contact'

  resources :answers
  resources :questions
  resources :quizzes
  resources :profiles
	devise_for :users, controllers: { registrations: "registrations" }
	resources :users
  get 'home/index'
  root 'home#index'
  resources :quizzes, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  # accepts_nested_attributes_for :user

  validates :first_name, :last_name, :year, :gender, :email, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:new, :create]
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @user = User.create(email: @profile.email, password: Devise.friendly_token.first(8))
    @profile.user = @user 

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :school, :year, :gender, :user_id, :email)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_nested_form_for(profile) do |f| %>
  <%= f.error_notification %>
  
      
      <div class="row">
        <div class="col-md-6">
          <%= f.input :first_name, autofocus: true %>
        </div>
        <div class="col-md-6">
          <%= f.input :last_name %>
        </div>
      </div>
      <%= f.input :email %>
      <%= f.input :year, label: 'Age', collection: ['18-21', '22-26', '27-35', '35+', 'Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11', 'Year 12'], include_blank: false %>
      <%= f.input :gender, collection: ['Female', 'Male', 'Non-binary / Third gender', 'Prefer not to say'], include_blank: false %>
  
  <div class="actions">
    <%= f.submit 'Start the quiz', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>School</th>
      <th>Year</th>
      <th>Gender</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.school %></td>
        <td><%= profile.year %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-body">
<h1>Create your Profile</h1>

<%= render 'form', profile: @profile %>
</div></div></div></div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>School:</strong>
  <%= @profile.school %>
</p>

<p>
  <strong>Year:</strong>
  <%= @profile.year %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.gender %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Start Quiz', quizzes_path, method: :post %>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>