config/routes.rb
Rails.application.routes.draw do
  resources :question_types
  get 'admin', to: 'pages#admin'
  get 'choose_age_group', to: 'pages#choose_age_group'

  get 'pages/about'

  get 'pages/contact'

  resources :answers
  resources :questions
  resources :quizzes
  resources :profiles
	devise_for :users, controllers: { registrations: "registrations" }
	resources :users
  get 'home/index'
  root 'home#index'
  resources :quizzes, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  has_many :user_quiz_answers
  has_many :user_quizzes, through: :user_quiz_answers

  mount_uploader :image, AnswerImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  # accepts_nested_attributes_for :user

  validates :first_name, :last_name, :year, :gender, :email, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :quiz_questions
	has_many :quizzes, through: :quiz_questions
	has_many :answers
	belongs_to :question_type
	accepts_nested_attributes_for :answers
	
end

app/models/question_type.rb
class QuestionType < ApplicationRecord
	has_many :questions
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	has_many :quiz_questions
	has_many :questions, through: :quiz_questions
	has_many :user_quizzes
   	has_many :users, through: :user_quizzes
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  belongs_to :quiz
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
	has_one :profile
	# accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_one :profile
   has_many :user_quizzes
   has_many :quizzes, through: :user_quizzes

end

app/models/user_quiz.rb
class UserQuiz < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
  has_many :user_quiz_answers
  has_many :answers, through: :user_quiz_answers
end

app/models/user_quiz_answer.rb
class UserQuizAnswer < ApplicationRecord
  belongs_to :user_quiz
  belongs_to :answer
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def admin
  end

  def about
  end

  def contact
  end

  def choose_age_group
  end

  def my_quiz
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/question_types_helper.rb
module QuestionTypesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">THE FOOTNOTES GAME</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <!--  <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
     <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Student Sign Up', new_user_registration_path(user_type: 'Student') %></li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">OTHER OPTIONS <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin">Admin</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to '<i class="fa fa-sign-out"></i> Sign out'. html_safe, destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footnotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <%= render 'layouts/navbar' %>
     <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/admin.html.erb
<h1>Admin</h1>
<p></p>
<%= link_to 'Quizzes', quizzes_path, class: 'btn btn-primary' %>
<%= link_to 'Questions', questions_path, class: 'btn btn-primary' %>
<%= link_to 'Answers', answers_path, class: 'btn btn-primary' %>
<%=link_to 'Users', users_path, class: 'btn btn-primary' %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/my_quiz.html.erb
Yay